# Copyright (C) Markus Witt
#
# SPDX-License-Identifier: CC0-1.0

services:
  travelynx:
    build: .
    volumes:
      - ./travelynx.conf:/app/travelynx.conf
      - ./travelynx-conf:/app/local
    ports:
      - 127.0.0.1:8000:8093
    links:
      - db
    restart: unless-stopped

  cron:
    build: .
    volumes:
      - ./travelynx.conf:/app/travelynx.conf
      - ./travelynx-conf:/app/local
    command: worker
    links:
      - db
    restart: unless-stopped

  db:
    image: postgres:17
    env_file: db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped

