# Copyright (C) Markus Witt
#
# SPDX-License-Identifier: CC0-1.0

version: "3.6"
  
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "travelynx" 
      POSTGRES_USER: "travelynx"
      POSTGRES_PASSWORD: "travelynx"

  travelynx:
    build: .
    volumes:
     - ./docker/travelynx.conf:/app/travelynx.conf:ro
     - ./docker/email-transport.sh:/app/local/email-transport.sh:ro
    ports:
      - "8000:8093"
    env_file: ./docker/.env

  cron:
    build: .
    volumes:
     - ./docker/travelynx.conf:/app/travelynx.conf:ro
     - ./docker/email-transport.sh:/app/local/email-transport.sh:ro
    env_file: ./docker/.env
    environment:
      CRON: 1