#!/bin/sh

# Copyright (C) 2020 Daniel Friesel <daniel.friesel@uos.de>
#
# SPDX-License-Identifier: MIT

set -x

for theme in dark light; do
	sassc -t compressed sass/src/${theme}/index.scss public/static/css/${theme}.min.css
done

for file in autocomplete geolocation travelynx-actions; do
	uglifyjs public/static/js/${file}.js -c -m > public/static/js/${file}.min.js
done
